### ISSUE TITLE
Update algoexplorer API endpoints

### ISSUE THREAD

**Issue by thecryptomie** [algokittens/algoNFTs#13]
The API endpoints listing in the `lib/settings.py` module need to be updated to reflect changes made by algoexplorer.

At the end of Feb 2022, the original endpoints were deprecated and are no longer in service. When trying to batch mint some NFTs, this results in an 404 that gets obscured by nested try/except statements in the `algosdk`. 

MWE 1: Failure
---------------
```python
from algosdk.v2client import algod
algod_address = "https://api.testnet.algoexplorer.io"
algod_client = algod.AlgodClient('', algod_address, headers={'User-Agent': 'DoYouLoveMe?'})
params = algod_client.suggested_params()
```

MWE 2: Success
------------------
```python
from algosdk.v2client import algod
algod_address = "https://node.algoexplorerapi.io"
algod_client = algod.AlgodClient('', algod_address, headers={'User-Agent': 'DoYouLoveMe?'})
params = algod_client.suggested_params()
```

**Comment by algokittens** [comment]
This has now been fixed, thanks for the heads up!
