### ISSUE TITLE
How can I verify Minting ??

### ISSUE THREAD

**Issue by awaisahmadfg** [algokittens/algoNFTs#15]
![transactions](https://user-images.githubusercontent.com/58293801/171128871-7d94957c-bd24-4cf6-9648-41398944b864.png)

- **I checked at Randgallery.com, No image is showing. Kindly AnyOne can guide me about this !!**

**Comment by algokittens** [comment]
Hi,

Could you please share the account address used? 
If this is the correct address I can't find it on the blockchain explorer/ it is not a valid address. 7URWD60PEAJTIFSYDQJL7YI2NK6E6UK4SSUCT0DZEIHQHN57ADBL3G6Q2A

Maybe there is a typo somewhere?

**Comment by awaisahmadfg** [comment]
Dear, I checked there is no typo in my address.
I really appreciate if there is any other thing you want to point out.

**Comment by algokittens** [comment]
Thanks for confirming - this is very strange. How did you create the address? Are there any algos on it (either on the testnet or mainnet)?
If I try to seed the testnet account on https://bank.testnet.algorand.network/ it gives me the following error:

> Status: Code 500 error: failed to dispense money - failed to decode address 7URWD60PEAJTIFSYDQJL7YI2NK6E6UK4SSUCT0DZEIHQHN57ADBL3G6Q2A to base 32

And like I said, I can't find it on the blockchain explorer:
https://algoexplorer.io/
or:
https://goalseeker.purestake.io/algorand/

Are you able to import the wallet to MyAlgo or Pera wallet (or any others)?

**Comment by awaisahmadfg** [comment]
I created the address at MyAlgo wallet, My address is : 7URWD6OPEAJTIFSYDQJL7YI2NK6E6UK4SSUCTODZEIHQHN57ADBL3G6Q2A
Yess there are algos in testnet.

Attach are some Screnshots.
![Up1](https://user-images.githubusercontent.com/58293801/171261009-7fa55aaf-77d2-4cef-bd6b-8bb5df48030b.png)
![up2](https://user-images.githubusercontent.com/58293801/171261077-cbc8c212-079e-439f-b2bb-d4aab55ea62d.png)
![up6](https://user-images.githubusercontent.com/58293801/171262467-737f3903-c581-4c44-917b-e71665069baa.png)
![up3](https://user-images.githubusercontent.com/58293801/171261137-91b5dd23-2db8-4ca9-9651-161c990d3863.png)
![up4](https://user-images.githubusercontent.com/58293801/171261149-1d628dab-ab14-4c19-8214-e2da851acdcf.png)

**Comment by algokittens** [comment]
Thanks for sharing that address, it looks like there was a typo in the address I checked earlier. 
The way to check the NFT on the testnet is to add a &testnet flag to the randgallery link:
https://www.randgallery.com/algo-collection/?address=92912187&testnet
Although it seems randgallery currently is not fetching it correctly (which is an issue on their end - they don't always maintain the testnet side of their website). I can send them a message in their Discord.

In the meanwhile, the other way to check is on one of the blockchain explorers:
https://testnet.algoexplorer.io/tx/4PRTV76FWZKFZBOTYTI5QFQTNB3QPSIUBBR44DUJ6JWYUN36QZZQ
Where all the formatting looks fine :+1: .

**Comment by awaisahmadfg** [comment]
Noted
Thanks for the help
