### ISSUE TITLE
Could you please make a Video Tutorial/Walkthrough?

### ISSUE THREAD

**Issue by bigtoadsnft** [algokittens/algoNFTs#3]
Pretty new to code, and there's a few areas of your instructions which I don't understand Step 5 "Prepare Your Data" with spreadsheet, "Running the Script" Part 1: Download "config_mint.py" and "mint_arc69.py". I'm using the Hashlips generative art engine on VSCode. 

 A visual representation of the excel formatting would be helpful. Also unsure of how to download the python scripts- have tried using "install" command, etc..

Any help would be greatly appreciated!

**Comment by dbchristenson** [comment]
Hi big toads, I'm the main dev for the Mesiverse project and just finished the code for our auto minter for our first project. If you need some guidance you can dm me @mesiverse on twitter.

**Comment by bigtoadsnft** [comment]
Thank you, but Algokittens helped out a ton with everything so its all good.  He even updated the code to allow generators such as HashLips to work as well!
